### ISSUE TITLE
2015 steam?

### ISSUE THREAD

**Issue by WoolenDoolen** [eyedine2/Classic-Steam-Library#18]
hi

i was wondering if you know of a theme like this but for the 2015 era of steam as attached. otherwise i love your skin thank you for making it. 
![image](https://github.com/eyedine2/Classic-Steam-Library/assets/84048395/f35fe232-2a43-4f76-89d8-d8c4378c7ed9)

**Comment by eyedine2** [comment]
I just updated the theme to add this lol

**Comment by WoolenDoolen** [comment]
oh i just noticed thank you. is there a plan to make play button blue

**Comment by eyedine2** [comment]
just did that, enjoy
