### ISSUE TITLE
Mouse icon on "PLAY" button

### ISSUE THREAD

**Issue by leonill007** [eyedine2/Classic-Steam-Library#21]
If possible, replace the triangle on the play button with the mouse icon, as seen in the attached screenshot
![steamworkshop_webupload_previewfile_192437033_preview](https://github.com/user-attachments/assets/5381766d-7823-4937-9178-3688e2558436)

**Comment by eyedine2** [comment]
I've wanted to do that, haven't been able to find that image though. Wasn't anywhere in steam's graphics folder I don't think. Might be in an old build from 2010.

**Comment by eyedine2** [comment]
done, styled a lot of the other play button images too and for both themes. Anything that I couldn't find will just have the Install image.
