### ISSUE TITLE
Classic Green version

### ISSUE THREAD

**Issue by DraconicNEO** [eyedine2/Classic-Steam-Library#22]
**Describe the solution you'd like**
Was wondering if it could be possible to create a classic green version, like the old classic theme of the 2004 steam client style. Since none of the original versions work anymore or work on Decky or CSSthemes.

**Additional context**
Mainly just to create another version of the theme but for the 2004 version, in addition to the one currently modeled here.

**Comment by eyedine2** [comment]
not really feasible in the current system or necessary since this exists https://steambrew.app/theme?id=8YTvx3fAAfwQSu6MNOfH

If you use deckthemes you should ask the author of that skin to add it to there.
