### ISSUE TITLE
[BUG] Cloud status covered with a scrollbar

### ISSUE THREAD

**Issue by Chrypson** [eyedine2/Classic-Steam-Library#23]
The cloud status is not visible, it's covered with a scrollbar

**Screenshots**
![Captura de pantalla 2024-08-18 221047](https://github.com/user-attachments/assets/a1d69aaf-74ec-4f36-b076-8325ee58c4bf)

 - OS: Windows 11 23H2

Steam language is set to Spanish (Latin America)

**Comment by eyedine2** [comment]
Should be fixed in 0ee14cc
