### ISSUE TITLE
[BUG] No game title in library?

### ISSUE THREAD

**Issue by blondedradio** [eyedine2/Classic-Steam-Library#5]
Updated the theme just now, and now none of my games don't have a title? 

![image](https://github.com/eyedine2/Classic-Steam-Library/assets/153567524/993cab5d-3a63-4b18-adb6-e9ab36d038b9)

Not opted into Steam Beta.

**Comment by blondedradio** [comment]
Reinstalled Steam and installed the theme from scratch - s'all good now.

**Comment by eyedine2** [comment]
that's odd
