### ISSUE TITLE
[BUG] Group chats do not show up in the friends menu

### ISSUE THREAD

**Issue by Veinhelm** [eyedine2/Classic-Steam-Library#9]
Title says it. When you open the friends menu, it wont show the group chats at the bottom of the menu.

Without theme:
![Screenshot_1 - Copy](https://github.com/eyedine2/Classic-Steam-Library/assets/61033221/e852b71a-6e5d-4988-8074-13e3311e14dd)

With theme:
![Screenshot_2 - Copy](https://github.com/eyedine2/Classic-Steam-Library/assets/61033221/45dd6cbd-698f-4dd0-abf4-9c1e2725f0b5)

**Comment by eyedine2** [comment]
Not a bug, they're removed since the element looks unfitting (and I didn't think anyone used group chats)

You can manually readd them if you want. Just delete everything from line `13` to `16` in `friends.custom.css`
